#define RP2040_MCUCONF		  TRUE
#define HAL_USE_I2C 		  TRUE
#define RP_IRQ_USB0_PRIORITY  FALSE
#define RP_IRQ_USB1_PRIORITY  FALSE
#define RP_IRQ_UART0_PRIORITY FALSE
#define RP_IRQ_UART1_PRIORITY FALSE 
#define RP_I2C_USE_I2C1 	  FALSE
#define RP_I2C_USE_I2C0       TRUE